version: '3'
services:
  jenkins:
    image: jenkins/jenkins:latest
    ports:
    - 8082:8080
    - 50000:50000
    volumes:
    - jenkins_home
    environment:
    - JAVA_OPTS="-XX:MaxPermSize=512m -Xms512m -Xmx1024m"
    networks:
    - jenkins

networks:
    jenkins: