- name: Ensure that ssh user is present
  user:
    name: "{{ deploy_user }}"
    shell: "{{ shell }}"
    state: present
    groups: sudo
    password: $6$rTE9hz9FZof$NlruI0YG7W/vWRpLhJdxGabKR3DsM5y8DvgCHgXlxnUmmdnyQYHO4ydJtQpKIzM76CPPGWf9ld2ty8BGj15BM/
    update_password: always
    append: yes
- name: Ensure that the user's .ssh directory exists
  file:
    path: "/home/{{ deploy_user }}/.ssh"
    state: directory
- name: Ensure public ssh key is in place
  copy:
    src: "~/.ssh/id_rsa.pub"
    dest: "/home/{{ deploy_user }}/.ssh/authorized_keys"
- name: Configure ssh daemon
  template:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
- name: Allow non-standard port through firewall
  ufw:
    rule: allow
    port: '{{ ssh_port }}'
- name: Restart ssh daemon
  service:
    name: sshd
    state: restarted